### ISSUE TITLE
npm module

### ISSUE THREAD

**Issue by yohei1126** [temyers/serverless-localstack#2]
It would be great to have a npm module for this. Thanks!

**Comment by temyers** [comment]
Hi Yohei,

Yes, this is still very much WIP.  Once it's properly up and running I'll add to NPM.

Contributions Welcome.

**Comment by franciscocpg** [comment]
hi @temyers 
I didn't find `serverless-localstack` in npm. It wasn't added to npm yet?

**Comment by temyers** [comment]
Once #18 is merged, I shall push to NPM

**Comment by temyers** [comment]
Now published to NPM!

current version is `0.2.1`
