### ISSUE TITLE
question about credentials in the example...

### ISSUE THREAD

**Issue by st33v** [temyers/serverless-localstack#25]
when I deploy the example, server less requires that I use credentials:

```
  Serverless Error ---------------------------------------

  The security token included in the request is invalid.
```

so, I configure it with 'real' credentials but when I invoke my lambda function using sls, the ARN of my function includes the 'real' account id:
```
Serverless: Invoke invoke

  Serverless Error ---------------------------------------

  Function not found: arn:aws:lambda:us-east-1:941957936246:function:aws-nodejs-dev-hello

  Stack Trace --------------------------------------------
```

while the lambda function ARN looks like:
```
 sneuharth@sneuharth-mbp  ~/Projects/service  awslocal lambda list-functions                                                                          
{
    "Functions": [
        {
            "FunctionName": "aws-nodejs-dev-hello",
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:aws-nodejs-dev-hello",
            "Runtime": "nodejs6.10",
            "Handler": "handler.hello",
            "CodeSize": 50,
            "Version": "$LATEST",
            "Environment": {}
        },
        {
            "FunctionName": "aws-nodejs-local-hello",
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:aws-nodejs-local-hello",
            "Runtime": "nodejs6.10",
            "Handler": "handler.hello",
            "CodeSize": 50,
            "Version": "$LATEST",
            "Environment": {}
        }
    ]
}
```

**Comment by st33v** [comment]
is there a way to use credentials with serverless that will give me the correct (fake) ARN?

**Comment by temyers** [comment]
Serverless framework requires fake credentials to be set:

in `~/.aws/credentials`:
```
[local]
aws_access_key_id = DUMMY
aws_secret_access_key = DUMMY
```

Setting your profile prior to running `serverless` commands should work:
`export AWS_PROFILE=local`

If it works for you, I'd appreciate a PR to update the documentation.

Thanks

**Comment by st33v** [comment]
Thanks @temyers that's how I have it set up currently and when I 

`sls deploy list -s local`

I get:
```
  Serverless Error ---------------------------------------

  The security token included in the request is invalid.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           9.7.1
     Serverless Version:     1.26.1
```

so sls seems to still try to communicate with AWS to validate my credentials.

**Comment by justinm** [comment]
> so sls seems to still try to communicate with AWS to validate my credentials.

This would appear so. Can you please copy/paste the relevant portion of your serverless.yml so we can take a look?

**Comment by justinm** [comment]
The error you're receiving still indicates an issue with your AWS profile. Please ensure that you run `export AWS_PROFILE=local` in each new terminal prior to running any serverless commands.

A good to confirm this is set properly is to `echo $AWS_PROFILE` to ensure the environment variable has been set properly.

**Comment by liangjacky** [comment]
this solution doesn't work anymore.
