### ISSUE TITLE
The specified bucket does not exist

### ISSUE THREAD

**Issue by meldehi** [temyers/serverless-localstack#29]
I keep getting this error. I verified the bucket exist and apparently the first upload for the cloud-formation file to s3 succeeds. Any idea what am I doing wrong here or is there a bug I am not aware of? Deployment to AWS works between. 

$ serverless deploy --verbose --aws-profile serverless
Serverless: Packaging service...
Serverless: Using serverless-localstack-plugin
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Validating template...
Serverless: Skipping template validation: Unsupported in Localstack
Serverless: Creating Stack...
 
  Serverless Error ---------------------------------------
 
  The specified bucket does not exist
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.9.4
     Serverless Version:     1.26.1

**Comment by justinm** [comment]
Can you please rerun with the --debug flag and provide it's output? In addition, please provide the plugins and custom sections from your serverless.yml.
