### ISSUE TITLE
serverless-plugin-localstack vs serverless-localstack

### ISSUE THREAD

**Issue by niron1** [temyers/serverless-localstack#31]
Hi,
in some places in the code it is written 'serverless-plugin-localstack' and in others 'serverless-localstack' could you care to explain the difference between the two? thanks

**Comment by justinm** [comment]
serverless-plugin-localstack was the original plugins name. It was renamed just prior to being published to NPM so that it's name matched the github repository.

The correct name is now serverless-localstack
