### ISSUE TITLE
Issue with using serverless and localstack

### ISSUE THREAD

**Issue by somu90091** [temyers/serverless-localstack#34]
Hi,

I am using sls deploy with localstack configured. I am getting the below error:
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Using serverless-localstack-plugin
 
  Serverless Error ---------------------------------------
 
  ServerlessError: Service Unavailable
 

When Accessing the localstack resources from code, it is working. Only when trying to deploy on local using serverless, it is failing. 
Kindly help me.

**Comment by justinm** [comment]
In order to further diagnose your issue kindly rerun your deployment using `SLS_DEBUG=* sls deploy` and provide it's output via [gist](gist.github.com). In addition, also provide your serverless.yaml.
