### ISSUE TITLE
Specified bucket does not exist

### ISSUE THREAD

**Issue by kurtisane** [temyers/serverless-localstack#35]
I'm running Localstack over Docker using "docker-compose up" and trying to deploy via "sls deploy --stage local".
I'm zipping the jar file that I created via "./gradlew deploy", which compiled my kotlin code to the jar.
I changed the package artifact to point to the zip.

Following errors 
`$ sls deploy --stage local --debug
Serverless: Packaging service...
Serverless: Loading endpointJson from localstack.json
Serverless: Intercepting service APIGateway
Serverless: Intercepting service CloudFormation
Serverless: Intercepting service CloudWatch
Serverless: Intercepting service DynamoDB
Serverless: Intercepting service DynamoDBStreams
Serverless: Intercepting service ES
Serverless: Intercepting service Firehose
Serverless: Intercepting service Kinesis
Serverless: Intercepting service Lambda
Serverless: Intercepting service Redshift
Serverless: Intercepting service Route53
Serverless: Intercepting service S3
Serverless: Intercepting service SES
Serverless: Intercepting service SNS
Serverless: Intercepting service SQS
Serverless: config.options_stage: local
Serverless: serverless.service.custom.stage: undefined
Serverless: serverless.service.provider.stage: dev
Serverless: Using serverless-localstack-plugin
Serverless: Reconfiguring service APIGateway to use http://localhost:4567
Serverless: Reconfiguring service CloudFormation to use http://localhost:4581
Serverless: Reconfiguring service CloudWatch to use http://localhost:4582
Serverless: Reconfiguring service DynamoDB to use http://localhost:4569
Serverless: Reconfiguring service DynamoDBStreams to use http://localhost:4570
Serverless: Reconfiguring service ES to use http://localhost:4571
Serverless: Reconfiguring service Firehose to use http://localhost:4573
Serverless: Reconfiguring service Kinesis to use http://localhost:4568
Serverless: Reconfiguring service Lambda to use http://localhost:4574
Serverless: Reconfiguring service Redshift to use http://localhost:4577
Serverless: Reconfiguring service Route53 to use http://localhost:4580
Serverless: Reconfiguring service S3 to use http://localhost:4572
Serverless: Reconfiguring service SES to use http://localhost:4579
Serverless: Reconfiguring service SNS to use http://localhost:4575
Serverless: Reconfiguring service SQS to use http://localhost:4576

  Serverless Error ---------------------------------------

  The specified bucket does not exist

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           8.11.1
     Serverless Version:     1.27.2`

and the docker-compose terminal shows :
`localstack_1  | 2018-05-19T07:32:44:ERROR:localstack.services.generic_proxy: Error forwarding request: An error occurred (ValidationError) when calling the DescribeStackResources operation: Stack with id pv-jvm-core-localstack-local does not exist Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 215, in forward
localstack_1  |     updated_response = self.proxy.update_listener.return_response(**kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 216, in return_response
localstack_1  |     template_deployer.deploy_template(template, req_data.get('StackName')[0])
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 484, in deploy_template
localstack_1  |     stack_resources = describe_stack_resources(stack_name, resource_id)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 218, in describe_stack_resources
localstack_1  |     resources = client.describe_stack_resources(StackName=stack_name, LogicalResourceId=logical_resource_id)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
localstack_1  |     return self._make_api_call(operation_name, kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
localstack_1  |     raise error_class(parsed_response, operation_name)
localstack_1  | ClientError: An error occurred (ValidationError) when calling the DescribeStackResources operation: Stack with id pv-jvm-core-localstack-local does not exist
localstack_1  |
`

What is happening here ?

**Comment by you-fail-me** [comment]
I'm having a similar issue. Running localstack via `localstack start`, running `sls deploy --stage local` getting `The specified bucket does not exist`. Did you have any luck figuring this out?

**Comment by garethmcc** [comment]
I was just investigating this some more and noticed the following:
1. On deployment the logs show the following for CloudFormation where I set the port for CloudFormation in serverless.yml to be 4950
```Reconfiguring service CloudFormation to use http://localhost:4950```

All good so far

2. Later on the same deploy, however, I see the following:
```Using custom endpoint for CloudFormation: http://localhost:4572```

This is actually the endpoint for S3.

3. Looking into the code for the plugin, in index.js on line 142 I find:
```this.debug(`Using custom endpoint for ${service}: ${AWS.config['s3'].endpoint}`);```

Is it possible that an attempt to call CloudFormation is being incorrectly changed to calling S3?

**Comment by justinm** [comment]
It looks like there is an issue in the debug message itself, not with how the endpoint is being overridden. I've submitted a PR to fix the debug message.

In regards to your original issue, I recommend retrying using the latest version of Localstack. Please see [Localstack](https://github.com/localstack/localstack) on how to retrieve and install the latest version of Localstack.

**Comment by theogravity** [comment]
I'm having this problem too. Using the latest version of Localstack, and using the example files from this repo.

```
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.14.1
     Serverless Version:     1.35.1
```

**Comment by theogravity** [comment]
Note that this error happens after a second attempt at trying to deploy. The first attempt does:

```
Serverless: Creating Stack...
Serverless: Recoverable error occurred (null), sleeping for 5 seconds. Try 1 of 4
Serverless: Recoverable error occurred (null), sleeping for 5 seconds. Try 2 of 4
Serverless: Recoverable error occurred (null), sleeping for 5 seconds. Try 3 of 4
Serverless: Recoverable error occurred (null), sleeping for 5 seconds. Try 4 of 4
 
  Serverless Error ---------------------------------------
 
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.14.1
     Serverless Version:     1.35.1
```
