### ISSUE TITLE
500 Internal Server Error after "Updating Stack" starts

### ISSUE THREAD

**Issue by justinm** [temyers/serverless-localstack#38]
When running `sls deploy` in example/service with the latest version of localstack (has the boto3-1.4.3 patch) an error occurs while updating the deployed stack:

`
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (627 B)...
Serverless: Validating template...
Serverless: Skipping template validation: Unsupported in Localstack
Serverless: Updating Stack...
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
`

If localstack is run with DEBUG=1, `KeyError: 'AWS::Partition'` is being thrown.

I believe this is an upstream issue in the moto library, specifically AWS::Partition is not an available attribute to CloudFormation templates, which is an attribute Serverless uses when constructing it's references. https://gist.github.com/justinm/91a315ec604fc7c6c33ff89f7ce7fff8 is an example of this.

**Comment by justinm** [comment]
Issue submitted upstream to Moto https://github.com/spulec/moto/issues/1816 and Localstack https://github.com/localstack/localstack/issues/925. As a workaround, see the patch https://github.com/spulec/moto/pull/1817/commits/d60d562c6262e5e2b58a2d8e5ee9f5f12eb09fc3

**Comment by theogravity** [comment]
I've spent two days trying to figure this out, including with the patch - not having any successes. My thought is to not use localstack if possible.

**Comment by mikaelwecode** [comment]
I gave up trying to get serverless working with localstack. 

I user serverless-offline instead and serverless-dynamodb-local. Then just connect to localstacks dynamodb instance. It works pretty good for local development :)

**Comment by theogravity** [comment]
@mikaelwecode thanks for the suggestion - `serverless-offline` worked for me, although I have other aws services I need to provision as well

**Comment by mikaelwecode** [comment]
No problem! 

I use sns, sqs and dynamodb and fake the cognito headers with serverless-offline.  If you need any of them?  I can try to help!  :)

**Comment by jpcbarros** [comment]
+1 having the same issue

**Comment by msolimans** [comment]
@mikaelwecode how did you fake the headers for cognito to make it working locally, any code snippet would be great. appreciated

**Comment by mikaelwecode** [comment]
@msolimans I added them if  local.   

I just created a function called headers.js se below
`
export const headers = async () => {
  if (process.env.REACT_APP_USE_LOCALHOST) {
    const user = await getUser();
    return { "cognito-authentication-provider": user["sub"] };
  }
  return {};
};
`
Then I call this function when doing api call. I use aws-amplify. 
`  
export const getItem = async id => {
  try {
    const item = await API.get(
      "apiname",
      "myapipath.com/getitem/" + id,
      { headers: await headers() }
    );
    return item;
  } catch (e) {
    console.log(e);
    throw e;
  }
};
`

Hope it helps!
