### ISSUE TITLE
DeploymentBucket usage in serverless.yml Error

### ISSUE THREAD

**Issue by prr19776** [temyers/serverless-localstack#42]
If i use that deploymentBucket in the sls yml , im getting some error as below , is there any issue in the code or my setup in aws config/credential file is messed up ?

  Serverless Error ---------------------------------------
 
  Could not locate deployment bucket. Error: The AWS Access Key Id you provided does not exist in our records.

**Comment by justinm** [comment]
This is likely a configuration issue. Can you please retry your deployment using the --debug flag and provide it's output? Also, please provide the plugins and custom sections from your serverless.yml.
