### ISSUE TITLE
Only deploy is supported, other serverless commands like invoke are not

### ISSUE THREAD

**Issue by rreynier** [temyers/serverless-localstack#48]
Only `sls deploy` is supported.  All other serverless commands do not leverage this integration. The solution is to tap into more hooks for the different commands.  (https://github.com/temyers/serverless-localstack/blob/master/src/index.js#L16-L18)

For example the invoke function: `sls invoke --function funtionName` does not get reconfigured to use localstack. 

Another function that could use support is `sls deploy list functions`. 

I was considering publishing a PR to add more support, but wanted to understand if this is intended to work as is?

**Comment by suryacaprice** [comment]
Hi  @rreynier 
Were you able to deploy successfully, Can you please share your steps and the configuration? For some reason, my deployments were not working.

**Comment by rreynier** [comment]
@suryacaprice I was, I actually had to modify local stack a bit. What deploy errors are you getting?

**Comment by suryacaprice** [comment]
Can you please share me your modifications ..

**Comment by temyers** [comment]
This project is no longer being actively maintained, so shall be archiving the repository
