### ISSUE TITLE
Define provider

### ISSUE THREAD

**Issue by djKooks** [temyers/serverless-localstack#6]
Hello! Hope this is not a dumb question.
I faced an error like below after setup.(I installed without npm)
```
Serverless Error ---------------------------------------
 
  "provider" property is missing in serverless.yml
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
```
How can I define provider to access to local stack? I couldn't find guide in README about this.

Thanks.

**Comment by temyers** [comment]
See https://github.com/temyers/serverless-localstack/blob/master/example/service/serverless.yml

```
provider:
  name: aws
  runtime: nodejs6.10
```

perhaps incorrect indentation?

Please note this is still very WIP - but please let me know your experiences! :)

**Comment by djKooks** [comment]
@temyers Thanks.
Now I tested with example updated here. I got problem like below.
```
$serverless deploy
  Serverless Error ---------------------------------------
 
  ServerlessError: AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: https://git.io/vXsdd.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           7.6.0
     Serverless Version:     1.17.0
```
Do I have to run with other command instead of `serverless deploy` to access on localstack?

**Comment by adieuadieu** [comment]
@djKooks the AWS SDK (which is what Serverless uses) requires that you specify credentials, even if you're using localstack. You can export some dummy ones:

```bash
export AWS_ACCESS_KEY_ID=foobar
export AWS_SECRET_ACCESS_KEY=foobar
export AWS_DEFAULT_REGION=us-east-1

serverless deploy
```

@temyers This is perhaps something that could be done automatically in the plugin if not already set in `process.env`?

**Comment by djKooks** [comment]
@adieuadieu Thanks! But I got a new issue after add your settings.
```
Serverless Error ---------------------------------------
 
  ServerlessError: The security token included in the request is invalid.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           7.6.0
     Serverless Version:     1.17.0
```
I tried `export AWS_SESSION_TOKEN=foobar`, but it causes same error.

**Comment by adieuadieu** [comment]
@djKooks would it be possible for you to share your `serverless.yml` file here? I'm interested in seeing the `plugins` and `custom` sections.

**Comment by djKooks** [comment]
@adieuadieu Sure. I used the one in example file.
```
service: aws-nodejs

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-localstack

custom:
  localstack:
    endpoint: localstack_endpoints.json

functions:
  hello:
    handler: handler.hello
    events:
```
And localstack_endpoints.json
```
{
    "APIGateway": "http://localhost:4567",
    "CloudFormation": "http://localstack:4581",
    "CloudWatch":"http://localhost:4582",
    "DynamoDB": "http://localstack:4569",
    "DynamoDBStreams": "http://localhost:4570",
    "ES": "http://localhost:4571",
    "Firehose": "http://localhost:4573",
    "Kinesis": "http://localstack:4568",
    "Lambda": "http://localstack:4574",
    "Redshift": "http://localstack:4577",
    "Route53": "http://localstack:4580",
    "S3": "http://localstack:4572",
    "SES": "http://localstack:4579",
    "SNS": "http://localstack:4575",
    "SQS": "http://localstack:4576"
}
```

**Comment by temyers** [comment]
Sorry guys, a bit late to the party here :)

>This is perhaps something that could be done automatically in the plugin if not already set in process.env?
@adieuadieu - I don't think that would be appropriate, since it might end up with unexpected behaviour.  Ultimately, I want to make the plugin work with a switch, so something like:
```
serverless deploy --localstack
```
Which would mean you can deploy to either AWS or localstack.
In addition, the custom endpoint solution isn't exclusive to localstack.  So again, don't think it's appropriate to tie it too closely to localstack itself.

I know the name suggests otherwise, but that makes it easy to find :)

@djKooks I guess the first check is to make sure it's actually hitting your localstack rather than AWS itself.
Does the `Using custom endpoint for ${service}: ${endpoint}` output?

Try setting the following to dummy values too:
```AWS_SESSION_TOKEN
AWS_SECURITY_TOKEN```

**Comment by djKooks** [comment]
@temyers How can I check custom endpoint for ${service}: ${endpoint} output?

**Comment by djKooks** [comment]
@temyers @adieuadieu Maybe it can be because I didn't define `host` in serverless.yml. I'll try again later.

**Comment by djKooks** [comment]
@temyers @adieuadieu Yes it was my problem that forgot to setup `host`. It works fine after added. But it also need to export AWS setups which @adieuadieu mentioned above.
Thanks for help!

**Comment by warnerpinz** [comment]
I have host configured in my serverless.yml, still I get the same error.
Any idea how to solve this would be very much appreciated.
